---
# vim:ff=unix ts=2 sw=2 ai expandtab

- name: install postgresql
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - python-psycopg2
    - postgresql
    - postgresql-contrib

- name: start postgresql service
  service:
    name: postgresql
    state: started
    enabled: yes

