---
# vim:ff=unix ts=2 sw=2 ai expandtab

- name: install postgresql
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - nginx

- name: start nginx service
  service:
    name: nginx
    state: started
    enabled: yes

