---
# vim:ff=unix ts=2 sw=2 ai expandtab
- name: set up tmux
  hosts: ubuntu
  tasks:

    - name: apt-get install
      become: true
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - tmux

    - name: set up tmux.conf
      template:
        src: templates/tmux.conf
        dest: ~/.tmux.conf

    - name: gem install
      become: true
      gem:
        name: "{{ item }}"
        state: latest
      with_items:
        - tmuxinator

    - name: create dirs
      file:
        state: directory
        path: "~/{{ item }}"
      with_items:
        - .tmuxinator

    - name: download tmuxinator.zsh
      get_url:
        url: https://raw.githubusercontent.com/tmuxinator/tmuxinator/master/completion/tmuxinator.zsh
        dest: ~/bin/tmuxinator.zsh

    - name: add config to zshrc
      lineinfile:
        dest: ~/.zshrc
        line: "{{ item }}"
      with_items:
        - 'source ~/bin/tmuxinator.zsh'

    - name: render tmuxinator project example
      template:
        src: templates/tmuxinator_project.yml
        dest: ~/.tmuxinator/example.yml
