---
# vim:ff=unix ts=2 sw=2 ai expandtab
- name: set up tmux
  hosts: ubuntu
  tasks:

    - name: apt-get install
      become: true
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - git
        - vim
        - zsh
        - tmux

    - name: gem install
      become: true
      gem:
        name: "{{ item }}"
        state: latest
      with_items:
        - tmuxinator

    - name: download tmuxinator.zsh
      get_url:
        url: https://raw.githubusercontent.com/tmuxinator/tmuxinator/master/completion/tmuxinator.zsh
        dest: ~/.bin/tmuxinator.zsh

    - name: add config to zshrc
      lineinfile:
        dest: ~/.zshrc
        line: "{{ item }}"
      with_items:
        - 'source ~/.bin/tmuxinator.zsh'
