---
# vim:ff=unix ts=2 sw=2 ai expandtab
- name: set up oh-my-zsh
  hosts: ubuntu
  tasks:

    - name: change shell to zsh for current user
      become: true
      user:
        name: "{{ user }}"
        shell: /usr/bin/zsh
        generate_ssh_key: yes

    - name: git clone oh-my-zsh
      git:
        repo: git://github.com/robbyrussell/oh-my-zsh.git
        dest: ~/.oh-my-zsh
        accept_hostkey: yes

    - name: copy oh-my-zsh zshrc
      copy:
        remote_src: True
        src: ~/.oh-my-zsh/templates/zshrc.zsh-template
        dest: ~/.zshrc
        force: no

    - name: change oh-my-zsh theme
      lineinfile:
        dest: ~/.zshrc
        regexp: "^ZSH_THEME"
        line: 'ZSH_THEME="zhann"'

    - name: download tmuxinator.zsh
      get_url:
        url: https://raw.githubusercontent.com/tmuxinator/tmuxinator/master/completion/tmuxinator.zsh
        dest: ~/.bin/tmuxinator.zsh

    - name: add config to zshrc
      lineinfile:
        dest: ~/.zshrc
        line: "{{ item }}"
      with_items:
        - 'alias open="nautilus"'
        - 'export EDITOR="vim"'
        - 'export WORKON_HOME=~/env'
        - 'source /usr/local/bin/virtualenvwrapper.sh'
        - 'source ~/.bin/tmuxinator.zsh'
