---
# vim:ff=unix ts=2 sw=2 ai expandtab
- name: bootstrap a ubuntu server
  hosts: ubuntu
  tasks:

    - name: apt-get install
      become: true
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - python-pip
        - python3-dev
        - python-psycopg2
        - postgresql
        - postgresql-contrib
        - silversearcher-ag
        - htop
        - tmux
        - tree
        - supervisor
        - git
        - zsh
        - vim

    - name: pip install
      become: true
      pip:
        name: "{{ item }}"
        state: latest
      with_items:
        - virtualenv
        - virtualenvwrapper

    - name: gem install
      become: true
      gem:
        name: "{{ item }}"
        state: latest
      with_items:
        - tmuxinator

    - name: start supervisor service
      become: true
      service:
        name: supervisor
        state: started
        enabled: yes

    - name: create gitconfig
      become: true
      file:
        path: "{{ item }}"
        state: touch
      with_items:
        - "/etc/gitconfig"

    - name: git config alias
      become: true
      git_config:
        scope: system  # so all user can use it
        name: "{{ item.name }}"
        value:  "{{ item.value }}"
      with_items:
        - { name: "alias.br", value: "branch"}
        - { name: "alias.co", value: "checkout"}
        - { name: "alias.ci", value: "commit"}
        - { name: "alias.st", value: "status"}
        - { name: "color.ui", value: "true"}

    - name: create dirs
      file:
        state: directory
        path: "~/{{ item }}"
      with_items:
        - git
        - env
        - static
        - media

- include: _zsh.yml
- include: _tmux.yml
