---
# vim:ff=unix ts=2 sw=2 ai expandtab
#

- name: install pip and common python packages
  become: true
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - virtualenv
    - virtualenvwrapper
    - ipython
    - pylint
    - ansible
    - django
