---

# - name: download sublime gpg file
  # get_url:
    # url: https://download.sublimetext.com/sublimehq-pub.gpg
    # dest: /tmp/sublimehq-pub.gpg

- name: add apt key for sublime text
  become: yes
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: add apt repo for sublime text
  become: yes
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    filename: 'sublime-text'
    state: present

- name: apt install sublime text
  become: yes
  apt:
    name: sublime-text
    state: latest
    update_cache: yes


