---
# vim:ff=unix ts=2 sw=2 ai expandtab

# - name: get latest vim code
  # git:
    # repo: 'https://github.com/vim/vim.git'
    # dest: '/tmp/vim'
    # clone: yes
    # update: yes
    # force: yes
    # version: master

# - name: config vim
  # shell: ./configure --prefix=/usr/ --with-features=huge --enable-pythoninterp --enable-rubyinterp --enable-python3interp
  # args:
    # chdir: '/tmp/vim'

# - name: make vim
  # shell: make
  # args:
    # chdir: '/tmp/vim'

# - name: make install vim
  # become: true
  # shell: make install
  # args:
    # chdir: '/tmp/vim'

# - name: create dirs
  # file:
    # path: '~/.vim/bundle'
    # state: directory

- name: install vimrc
  template:
    src: "templates/vimrc"
    dest: "~/.vim/vimrc"

- name: git clone Vundle.vim
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: '~/.vim/bundle/Vundle.vim'
    clone: yes
    update: yes
    force: yes
    version: master

- name: Vundle Plugin Clean and Install
  command: vim +PluginClean +qall & vim +PluginInstall +qall
  args:
    chdir: '~/.vim/'

- name: update and compile YCM
  shell: git pull & git submodule update --init --recursive & python install.py
  args:
    chdir: '~/.vim/bundle/YouCompleteMe/'
