---
# vim:ff=unix ts=2 sw=2 ai expandtab
#
- name: apt-get install
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - python-pip
    - python3-dev
    - silversearcher-ag
    - htop
    - tmux
    - tree
    - zsh
    - vim

- name: pip install
  become: true
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - virtualenv
    - virtualenvwrapper

- name: create dirs
  file:
    state: directory
    path: "~/{{ item }}"
  with_items:
    - git
    - env
    - bin
    - static
    - media
